# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "utils_nfcore_quantms_pipeline"
description: Pipeline completion utilities for the nf-core quantmsdiann pipeline
keywords:
  - utils
  - nf-core
  - quantms
components:
  - completionemail
  - completionsummary
  - imnotification
  - utils_nextflow_pipeline
  - utils_nfcore_pipeline
  - utils_nfschema_plugin
input:
  - ch_input:
      type: file
      description: |
        Channel containing pipeline execution summary or status information
output:
  - ch_completion_status:
      type: file
      description: |
        Channel containing pipeline completion status and summary information
  - versions:
      type: file
      description: |
        Software versions used in this subworkflow
authors:
  - "@bigbio"
maintainers:
  - "@bigbio"
