name: pmultiqc
description: A library for proteomics QC report based on MultiQC framework.
keywords:
  - MultiQC
  - QC
  - Proteomics
tools:
  - pmultiqc:
      description: |
        A library for proteomics QC report based on MultiQC framework.
      homepage: https://github.com/bigbio/pmultiqc/
      documentation: https://github.com/bigbio/pmultiqc/
input:
  - multiqc_inputs:
      type: file
      description: |
        Collection of files staged under results/ for MultiQC
        (e.g. experimental design, pipeline outputs, version files, config)
  - quantms_log:
      type: file
      description: Pipeline logo or log file staged alongside results
output:
  - report:
      type: file
      description: MultiQC report file
      pattern: "*.html"
  - quantmsdb:
      type: file
      description: Sqlite3 database file stored protein psm and quantification information
      pattern: "*.db"
  - data:
      type: dir
      description: MultiQC data dir
      pattern: "*_data"
  - versions:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
