lint:
  files_exist:
    - .github/workflows/ci.yml
    - .github/workflows/nf-test.yml
    - .gitignore
    - conf/modules.config
    - conf/test.config
    - conf/test_full.config
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - .github/.dockstore.yml
    - docs/README.md
    - .gitignore
  modules_config: false
  multiqc_config: false
  nextflow_config: false
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: Yasset Perez-Riverol
  description: Quantitative Mass Spectrometry nf-core workflow
  force: false
  is_nfcore: false
  name: quantmsdiann
  org: bigbio
  outdir: .
  version: 2.1.0
