# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "create_input_channel"
description: Subworkflow to create input channels from validated SDRF files (DIA only)
keywords:
  - input
  - channel
  - validation
  - dia
components:
  - sdrf/parsing
input:
  - ch_sdrf:
      type: file
      description: |
        Channel containing the SDRF file path
output:
  - ch_meta_config_dia:
      type: file
      description: |
        Channel containing DIA data configuration [meta, spectra_file]
  - ch_expdesign:
      type: file
      description: |
        Channel containing experimental design information
  - versions:
      type: file
      description: |
        Software versions used in this subworkflow
authors:
  - "@bigbio"
maintainers:
  - "@bigbio"
